name: Deploy FireMusic

on:
  push:
    branches:
      - lavalink-main

jobs:
  restart:
    runs-on: ubuntu-latest
    steps:
      - name: Restart Pterodactyl Server
        run: |
          curl -X POST \
            "${{ secrets.PTERO_PANEL_URL }}/api/client/servers/${{ secrets.PTERO_SERVER_ID }}/power" \
            -H "Authorization: Bearer ${{ secrets.PTERO_API_KEY }}" \
            -H "Content-Type: application/json" \
            --data '{"signal":"restart"}'